/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as appLayoutRouteRouteImport } from './routes/(app)/_layout/route'
import { Route as appLayoutCreateAgreementRouteImport } from './routes/(app)/_layout/create-agreement'
import { Route as appLayoutOverviewRouteImport } from './routes/(app)/_layout/overview'
import { Route as appLayoutSettingsRouteImport } from './routes/(app)/_layout/settings'
import { Route as appLayoutAgreementsIndexRouteImport } from './routes/(app)/_layout/agreements/index'
import { Route as appLayoutAgreementsAgreementIdRouteImport } from './routes/(app)/_layout/agreements/$agreementId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRouteRoute = appLayoutRouteRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutCreateAgreementRoute =
  appLayoutCreateAgreementRouteImport.update({
    id: '/create-agreement',
    path: '/create-agreement',
    getParentRoute: () => appLayoutRouteRoute,
  } as any)
const appLayoutOverviewRoute = appLayoutOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutSettingsRoute = appLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutAgreementsIndexRoute =
  appLayoutAgreementsIndexRouteImport.update({
    id: '/agreements/',
    path: '/agreements/',
    getParentRoute: () => appLayoutRouteRoute,
  } as any)
const appLayoutAgreementsAgreementIdRoute =
  appLayoutAgreementsAgreementIdRouteImport.update({
    id: '/agreements/$agreementId',
    path: '/agreements/$agreementId',
    getParentRoute: () => appLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/create-agreement': typeof appLayoutCreateAgreementRoute
  '/overview': typeof appLayoutOverviewRoute
  '/settings': typeof appLayoutSettingsRoute
  '/agreements/$agreementId': typeof appLayoutAgreementsAgreementIdRoute
  '/agreements/': typeof appLayoutAgreementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/create-agreement': typeof appLayoutCreateAgreementRoute
  '/overview': typeof appLayoutOverviewRoute
  '/settings': typeof appLayoutSettingsRoute
  '/agreements/$agreementId': typeof appLayoutAgreementsAgreementIdRoute
  '/agreements': typeof appLayoutAgreementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/(app)/_layout': typeof appLayoutRouteRouteWithChildren
  '/(app)/_layout/create-agreement': typeof appLayoutCreateAgreementRoute
  '/(app)/_layout/overview': typeof appLayoutOverviewRoute
  '/(app)/_layout/settings': typeof appLayoutSettingsRoute
  '/(app)/_layout/agreements/$agreementId': typeof appLayoutAgreementsAgreementIdRoute
  '/(app)/_layout/agreements/': typeof appLayoutAgreementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/create-agreement'
    | '/overview'
    | '/settings'
    | '/agreements/$agreementId'
    | '/agreements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/create-agreement'
    | '/overview'
    | '/settings'
    | '/agreements/$agreementId'
    | '/agreements'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/(app)/_layout'
    | '/(app)/_layout/create-agreement'
    | '/(app)/_layout/overview'
    | '/(app)/_layout/settings'
    | '/(app)/_layout/agreements/$agreementId'
    | '/(app)/_layout/agreements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  appLayoutRouteRoute: typeof appLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/create-agreement': {
      id: '/(app)/_layout/create-agreement'
      path: '/create-agreement'
      fullPath: '/create-agreement'
      preLoaderRoute: typeof appLayoutCreateAgreementRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/overview': {
      id: '/(app)/_layout/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof appLayoutOverviewRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/settings': {
      id: '/(app)/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appLayoutSettingsRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/agreements/': {
      id: '/(app)/_layout/agreements/'
      path: '/agreements'
      fullPath: '/agreements/'
      preLoaderRoute: typeof appLayoutAgreementsIndexRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/agreements/$agreementId': {
      id: '/(app)/_layout/agreements/$agreementId'
      path: '/agreements/$agreementId'
      fullPath: '/agreements/$agreementId'
      preLoaderRoute: typeof appLayoutAgreementsAgreementIdRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
  }
}

interface appLayoutRouteRouteChildren {
  appLayoutCreateAgreementRoute: typeof appLayoutCreateAgreementRoute
  appLayoutOverviewRoute: typeof appLayoutOverviewRoute
  appLayoutSettingsRoute: typeof appLayoutSettingsRoute
  appLayoutAgreementsAgreementIdRoute: typeof appLayoutAgreementsAgreementIdRoute
  appLayoutAgreementsIndexRoute: typeof appLayoutAgreementsIndexRoute
}

const appLayoutRouteRouteChildren: appLayoutRouteRouteChildren = {
  appLayoutCreateAgreementRoute: appLayoutCreateAgreementRoute,
  appLayoutOverviewRoute: appLayoutOverviewRoute,
  appLayoutSettingsRoute: appLayoutSettingsRoute,
  appLayoutAgreementsAgreementIdRoute: appLayoutAgreementsAgreementIdRoute,
  appLayoutAgreementsIndexRoute: appLayoutAgreementsIndexRoute,
}

const appLayoutRouteRouteWithChildren = appLayoutRouteRoute._addFileChildren(
  appLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  appLayoutRouteRoute: appLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
