/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as appLayoutRouteRouteImport } from './routes/(app)/_layout/route'
import { Route as appLayoutPageRouteImport } from './routes/(app)/_layout/$page'
import { Route as appLayoutCreateAgreementRouteImport } from './routes/(app)/_layout/create-agreement'
import { Route as appLayoutAgreementsAgreementIdRouteImport } from './routes/(app)/_layout/agreements/$agreementId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRouteRoute = appLayoutRouteRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutPageRoute = appLayoutPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutCreateAgreementRoute =
  appLayoutCreateAgreementRouteImport.update({
    id: '/create-agreement',
    path: '/create-agreement',
    getParentRoute: () => appLayoutRouteRoute,
  } as any)
const appLayoutAgreementsAgreementIdRoute =
  appLayoutAgreementsAgreementIdRouteImport.update({
    id: '/agreements/$agreementId',
    path: '/agreements/$agreementId',
    getParentRoute: () => appLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/workspace': typeof WorkspaceRoute
  '/$page': typeof appLayoutPageRoute
  '/create-agreement': typeof appLayoutCreateAgreementRoute
  '/agreements/$agreementId': typeof appLayoutAgreementsAgreementIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/workspace': typeof WorkspaceRoute
  '/$page': typeof appLayoutPageRoute
  '/create-agreement': typeof appLayoutCreateAgreementRoute
  '/agreements/$agreementId': typeof appLayoutAgreementsAgreementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/workspace': typeof WorkspaceRoute
  '/(app)/_layout': typeof appLayoutRouteRouteWithChildren
  '/(app)/_layout/$page': typeof appLayoutPageRoute
  '/(app)/_layout/create-agreement': typeof appLayoutCreateAgreementRoute
  '/(app)/_layout/agreements/$agreementId': typeof appLayoutAgreementsAgreementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/workspace'
    | '/$page'
    | '/create-agreement'
    | '/agreements/$agreementId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/workspace'
    | '/$page'
    | '/create-agreement'
    | '/agreements/$agreementId'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/workspace'
    | '/(app)/_layout'
    | '/(app)/_layout/$page'
    | '/(app)/_layout/create-agreement'
    | '/(app)/_layout/agreements/$agreementId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  WorkspaceRoute: typeof WorkspaceRoute
  appLayoutRouteRoute: typeof appLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/$page': {
      id: '/(app)/_layout/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof appLayoutPageRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/create-agreement': {
      id: '/(app)/_layout/create-agreement'
      path: '/create-agreement'
      fullPath: '/create-agreement'
      preLoaderRoute: typeof appLayoutCreateAgreementRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/agreements/$agreementId': {
      id: '/(app)/_layout/agreements/$agreementId'
      path: '/agreements/$agreementId'
      fullPath: '/agreements/$agreementId'
      preLoaderRoute: typeof appLayoutAgreementsAgreementIdRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
  }
}

interface appLayoutRouteRouteChildren {
  appLayoutPageRoute: typeof appLayoutPageRoute
  appLayoutCreateAgreementRoute: typeof appLayoutCreateAgreementRoute
  appLayoutAgreementsAgreementIdRoute: typeof appLayoutAgreementsAgreementIdRoute
}

const appLayoutRouteRouteChildren: appLayoutRouteRouteChildren = {
  appLayoutPageRoute: appLayoutPageRoute,
  appLayoutCreateAgreementRoute: appLayoutCreateAgreementRoute,
  appLayoutAgreementsAgreementIdRoute: appLayoutAgreementsAgreementIdRoute,
}

const appLayoutRouteRouteWithChildren = appLayoutRouteRoute._addFileChildren(
  appLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  WorkspaceRoute: WorkspaceRoute,
  appLayoutRouteRoute: appLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
